#!/usr/bin/env node
/**
 * Builds the committed `exports/` directory: the zero-quota, jsDelivr-servable
 * consumption path for OpenCard DB.
 *
 * Unlike `dist/indexes/` (gitignored, built for KV upload), `exports/` is
 * committed to the repo so tag-pinned jsDelivr URLs like
 *   https://cdn.jsdelivr.net/gh/thedavidweng/opencard-db@v0.1.0/exports/cards-all.json
 * resolve to immutable, edge-cached files with no Worker involved.
 *
 * Reuses buildIndexArtifacts() from build-indexes.ts, then also writes:
 *   - cards.csv  : one flat row per card (analyst / spreadsheet friendly)
 *   - cards.yaml : same objects as cards-all.json (JSON is valid YAML 1.2)
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildIndexArtifacts } from "./build-indexes.ts";
import { repoRoot, type Card } from "./lib.ts";

/** Columns emitted by cards.csv, in order. */
export const CSV_COLUMNS = [
  "id",
  "country",
  "segment",
  "issuer_id",
  "issuer",
  "network",
  "network_tier",
  "type",
  "status",
  "annual_fee_amount",
  "annual_fee_currency",
  "rewards_currency",
  "rate_type",
  "base_rate",
  "signup_bonus_amount",
  "signup_bonus_unit",
  "official_url",
  "last_verified",
] as const;

function get(obj: unknown, key: string): unknown {
  if (obj && typeof obj === "object") {
    return (obj as Record<string, unknown>)[key];
  }
  return undefined;
}

/** Render one value as a CSV cell: null/undefined → "", otherwise stringify. */
function cell(value: unknown): string {
  if (value === null || value === undefined) return "";
  return String(value);
}

/** RFC 4180 escaping: quote fields with comma, quote, CR or LF; double quotes. */
function escapeCsv(field: string): string {
  if (/[",\r\n]/.test(field)) {
    return `"${field.replace(/"/g, '""')}"`;
  }
  return field;
}

/** Flatten a card into the CSV column values (in CSV_COLUMNS order). */
export function cardToCsvRow(card: Card): string[] {
  const annualFee = get(card, "annual_fee");
  const rewards = get(card, "rewards");
  const baseRate = get(rewards, "base_rate");
  const signupBonus = get(card, "signup_bonus");

  const values: Record<(typeof CSV_COLUMNS)[number], unknown> = {
    id: get(card, "id"),
    country: get(card, "country"),
    segment: get(card, "segment"),
    issuer_id: get(card, "issuer_id"),
    issuer: get(card, "issuer"),
    network: get(card, "network"),
    network_tier: get(card, "network_tier"),
    type: get(card, "type"),
    status: get(card, "status"),
    annual_fee_amount: get(annualFee, "amount"),
    annual_fee_currency: get(annualFee, "currency"),
    rewards_currency: get(rewards, "currency"),
    rate_type: get(rewards, "rate_type"),
    base_rate: get(baseRate, "points_per_dollar"),
    signup_bonus_amount: get(signupBonus, "amount"),
    signup_bonus_unit: get(signupBonus, "unit"),
    official_url: get(card, "official_url"),
    last_verified: get(card, "last_verified"),
  };

  return CSV_COLUMNS.map((col) => escapeCsv(cell(values[col])));
}

/** Build the full cards.csv text (header + one row per card, LF-terminated). */
export function buildCardsCsv(cards: Card[]): string {
  const header = CSV_COLUMNS.map(escapeCsv).join(",");
  const rows = cards.map((c) => cardToCsvRow(c).join(","));
  return [header, ...rows].join("\n") + "\n";
}

/**
 * Build cards.yaml. JSON is a subset of YAML 1.2, so a document whose body is
 * the JSON array of cards is valid YAML. We prepend `#` comment lines (also
 * valid YAML) to document provenance. Consumers can parse it with any YAML
 * loader or, equivalently, any JSON loader after stripping the comment lines.
 */
export function buildCardsYaml(cards: Card[]): string {
  const header = [
    "# OpenCard DB — cards.yaml",
    "# Generated by scripts/build-exports.ts. Do not edit by hand.",
    "# JSON is valid YAML 1.2, so the body below is the same array of card",
    "# objects as cards-all.json and parses with any YAML or JSON loader.",
    "",
  ].join("\n");
  return header + JSON.stringify(cards, null, 2) + "\n";
}

export async function buildExports(): Promise<{
  outDir: string;
  cardCount: number;
  files: string[];
}> {
  const artifacts = await buildIndexArtifacts();
  const cards = artifacts["cards:all"];
  const outDir = path.join(repoRoot(), "exports");
  await mkdir(outDir, { recursive: true });

  const jsonWrites: [string, unknown][] = [
    ["meta.json", artifacts.meta],
    ["cards-all.json", artifacts["cards:all"]],
    ["cards-by-id.json", artifacts["cards:by-id"]],
    ["index-country.json", artifacts["index:country"]],
    ["index-issuer.json", artifacts["index:issuer"]],
    ["index-network.json", artifacts["index:network"]],
    ["index-network-tier.json", artifacts["index:network_tier"]],
  ];

  const files: string[] = [];
  for (const [name, value] of jsonWrites) {
    await writeFile(
      path.join(outDir, name),
      JSON.stringify(value, null, 2) + "\n",
      "utf8",
    );
    files.push(name);
  }

  await writeFile(path.join(outDir, "cards.csv"), buildCardsCsv(cards), "utf8");
  files.push("cards.csv");

  await writeFile(
    path.join(outDir, "cards.yaml"),
    buildCardsYaml(cards),
    "utf8",
  );
  files.push("cards.yaml");

  return { outDir, cardCount: cards.length, files };
}

async function main(): Promise<void> {
  const { cardCount, files } = await buildExports();
  console.log(
    `ok: wrote ${files.length} export files (${cardCount} cards) → exports/`,
  );
}

// Run when executed as CLI; when imported by tests, only export functions.
const entry = process.argv[1] ?? "";
if (entry.includes("build-exports")) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
